apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'app-2'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app-2
  source:
    path: 'test'
    repoURL: 'https://github.com/Intility/example-project-gitops.git'
    targetRevision: HEAD
  project: 'project-1'